"""initial schema

Revision ID: 7cdc00a5e14b
Revises: 
Create Date: 2026-08-03 06:28:15.735325+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cdc00a5e14b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_records',
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('triggered_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backup_records_created_at', 'backup_records', ['created_at'], unique=False)
    op.create_table('brands',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name', name='uq_brands_normalized_name')
    )
    op.create_table('categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_categories_slug')
    )
    op.create_index('ix_categories_parent_id', 'categories', ['parent_id'], unique=False)
    op.create_table('merchants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('connector_key', sa.String(length=128), nullable=False),
    sa.Column('logo_url', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_merchants_slug')
    )
    op.create_table('scheduler_job_runs',
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'RETRYING', name='job_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.Column('items_failed', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scheduler_job_runs_job_name_started_at', 'scheduler_job_runs', ['job_name', 'started_at'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_table('master_products',
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('match_confidence', sa.Enum('EXACT_IDENTIFIER', 'HIGH_CONFIDENCE', 'MEDIUM_CONFIDENCE', 'LOW_CONFIDENCE', 'MANUAL', name='match_confidence'), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('canonical_image_url', sa.String(length=1024), nullable=True),
    sa.Column('needs_manual_review', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_master_products_brand_id', 'master_products', ['brand_id'], unique=False)
    op.create_index('ix_master_products_category_id', 'master_products', ['category_id'], unique=False)
    op.create_table('search_history',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('query_text', sa.String(length=512), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('searched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_search_history_user_id', 'search_history', ['user_id'], unique=False)
    op.create_table('product_specifications',
    sa.Column('master_product_id', sa.UUID(), nullable=False),
    sa.Column('spec_key', sa.String(length=255), nullable=False),
    sa.Column('spec_value', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['master_product_id'], ['master_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_product_id', 'spec_key', name='uq_product_specifications_key')
    )
    op.create_index('ix_product_specifications_master_product_id', 'product_specifications', ['master_product_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('master_product_id', sa.UUID(), nullable=False),
    sa.Column('variant_label', sa.String(length=255), nullable=False),
    sa.Column('upc', sa.String(length=64), nullable=True),
    sa.Column('ean', sa.String(length=64), nullable=True),
    sa.Column('gtin', sa.String(length=64), nullable=True),
    sa.Column('mpn', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['master_product_id'], ['master_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_variants_ean', 'product_variants', ['ean'], unique=False)
    op.create_index('ix_product_variants_master_product_id', 'product_variants', ['master_product_id'], unique=False)
    op.create_index('ix_product_variants_mpn', 'product_variants', ['mpn'], unique=False)
    op.create_index('ix_product_variants_upc', 'product_variants', ['upc'], unique=False)
    op.create_table('merchant_offers',
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('merchant_sku', sa.String(length=255), nullable=False),
    sa.Column('merchant_product_url', sa.String(length=2048), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('shipping_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('availability', sa.Enum('IN_STOCK', 'LOW_STOCK', 'OUT_OF_STOCK', 'PREORDER', 'DISCONTINUED', 'UNKNOWN', name='offer_availability'), nullable=False),
    sa.Column('estimated_delivery_days', sa.Integer(), nullable=True),
    sa.Column('rating_average', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('commission_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_price >= 0', name='ck_merchant_offers_price_nonnegative'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'merchant_sku', name='uq_merchant_offers_merchant_sku')
    )
    op.create_index('ix_merchant_offers_merchant_id', 'merchant_offers', ['merchant_id'], unique=False)
    op.create_index('ix_merchant_offers_variant_id', 'merchant_offers', ['variant_id'], unique=False)
    op.create_table('product_images',
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('cdn_url', sa.String(length=2048), nullable=True),
    sa.Column('thumbnail_cdn_url', sa.String(length=2048), nullable=True),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('perceptual_hash', sa.String(length=64), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_images_variant_id', 'product_images', ['variant_id'], unique=False)
    op.create_table('product_reviews',
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_reviews_variant_id', 'product_reviews', ['variant_id'], unique=False)
    op.create_table('affiliate_links',
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('link_token', sa.String(length=64), nullable=False),
    sa.Column('destination_url', sa.String(length=2048), nullable=False),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('last_clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['merchant_offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link_token', name='uq_affiliate_links_token')
    )
    op.create_index('ix_affiliate_links_offer_id', 'affiliate_links', ['offer_id'], unique=False)
    op.create_table('coupons',
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=True),
    sa.Column('coupon_type', sa.Enum('PERCENTAGE_OFF', 'FIXED_AMOUNT_OFF', 'FREE_SHIPPING', 'BUNDLE', name='coupon_type'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['merchant_offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_coupons_offer_id', 'coupons', ['offer_id'], unique=False)
    op.create_table('price_history',
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('availability', sa.Enum('IN_STOCK', 'LOW_STOCK', 'OUT_OF_STOCK', 'PREORDER', 'DISCONTINUED', 'UNKNOWN', name='offer_availability'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['merchant_offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_history_offer_id_recorded_at', 'price_history', ['offer_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_price_history_offer_id_recorded_at', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index('ix_coupons_offer_id', table_name='coupons')
    op.drop_table('coupons')
    op.drop_index('ix_affiliate_links_offer_id', table_name='affiliate_links')
    op.drop_table('affiliate_links')
    op.drop_index('ix_product_reviews_variant_id', table_name='product_reviews')
    op.drop_table('product_reviews')
    op.drop_index('ix_product_images_variant_id', table_name='product_images')
    op.drop_table('product_images')
    op.drop_index('ix_merchant_offers_variant_id', table_name='merchant_offers')
    op.drop_index('ix_merchant_offers_merchant_id', table_name='merchant_offers')
    op.drop_table('merchant_offers')
    op.drop_index('ix_product_variants_upc', table_name='product_variants')
    op.drop_index('ix_product_variants_mpn', table_name='product_variants')
    op.drop_index('ix_product_variants_master_product_id', table_name='product_variants')
    op.drop_index('ix_product_variants_ean', table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index('ix_product_specifications_master_product_id', table_name='product_specifications')
    op.drop_table('product_specifications')
    op.drop_index('ix_search_history_user_id', table_name='search_history')
    op.drop_table('search_history')
    op.drop_index('ix_master_products_category_id', table_name='master_products')
    op.drop_index('ix_master_products_brand_id', table_name='master_products')
    op.drop_table('master_products')
    op.drop_table('users')
    op.drop_index('ix_scheduler_job_runs_job_name_started_at', table_name='scheduler_job_runs')
    op.drop_table('scheduler_job_runs')
    op.drop_table('merchants')
    op.drop_index('ix_categories_parent_id', table_name='categories')
    op.drop_table('categories')
    op.drop_table('brands')
    op.drop_index('ix_backup_records_created_at', table_name='backup_records')
    op.drop_table('backup_records')
    # ### end Alembic commands ###

